---
abstract: 'The Standard Perl 6 Grammar'
author:
  - 'Larry Wall <larry@wall.org>'
  - "Stefan O'Rear <stefanor@cox.net>"
  - 'Pawel Murias <pawelmurias@gmail.com>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102221, CPAN::Meta::Converter version 2.101670'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: STD
requires:
  File::ShareDir: 1.02
  Moose: 0
  YAML::XS: 0
  perl: v5.10
version: 32115
